services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      # dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./applications/public:/var/www/html/public
    networks:
      - app-network
    env_file: "webapp.env"
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - ${PHP_PORT:-9000}:9000
    volumes:
      - ./applications:/var/www/html
    networks:
      - app-network
    env_file: "webapp.env"

networks:
  app-network:
    driver: bridge
