services:
  php-base:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./working-directory:/var/www/html
    env_file:
      - "webapp.env"
      - "working-directory/.env"
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      # dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
      - mysql
    ports:
      - ${WEB_PORT:-80}:80
      - ${WEB_PORT_SECURE:-443}:443
    volumes:
      - ./working-directory/public:/var/www/html/public
      - ./working-directory/storage:/var/www/html/storage
    networks:
      - app-network
    env_file:
      - "webapp.env"
      - "working-directory/.env"

  php:
    extends:
      service: php-base
    container_name: php
    ports:
      - ${PHP_PORT:-9000}:9000
    depends_on:
      - mysql

  composer:
    extends:
      service: php-base
    container_name: composer
    entrypoint: [ "composer" ]

  artisan:
    extends:
      service: php-base
    container_name: artisan
    entrypoint: [ "php", "artisan" ]

  mysql:
    container_name: mysql
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - app-network
    env_file:
      - "webapp.env"
      - "working-directory/.env"

  npm:
    container_name: npm
    image: node:lts-alpine
    working_dir: /var/www/html
    volumes:
      - ./working-directory:/var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - app-network
    env_file:
      - "webapp.env"
      - "working-directory/.env"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: 'local'
