services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./applications/public:/var/www/html/public
    networks:
      - app-network
    env_file: "webapp.env"

networks:
  app-network:
    driver: bridge
